
version: '3'

services:
  strapi:
    build:
      dockerfile: strapi.dockerfile
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./app:/srv/app
    ports:
      - '${HTTP_PORT}:1337'
    networks:
      - strapi
    depends_on:
      - database

  database:
    restart: unless-stopped
    env_file: .env
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - strapi

networks:
  strapi: